assorted desktop changes (#76)
- create a unified color palette
- make sketchybar multi-monitor aware
- make git aliases work with worktrees
- make aerospace work with more than 10 spaces

Signed-off-by: Nick Santos <nicholas.j.santos@gmail.com>

diff --git a/bin/git-start b/bin/git-start
--- a/bin/git-start
+++ b/bin/git-start
@@ -1,35 +1,46 @@
 #!/bin/bash
 
-set -u
+set -ux
 
 # Usage: git start <branch-name>
 if [ "$#" -ne 1 ] ; then
-    echo -e "\033[1;31mUsage: git start <branch-name>\033[0m"
-    exit 1
-fi
-
-git diff --quiet && git diff --cached --quiet
-if [ $? -ne 0 ] ; then
-    echo -e "\033[1;31mYou have uncommitted changes. Please commit or stash them before running git-sync.\033[0m"
-    exit 1
-fi
-
-username=$(gh api user --jq .login)
-if [ -z "$username" ] ; then
-    echo -e "\033[1;31mCould not determine GitHub username. Make sure you are logged in with 'gh auth login'.\033[0m"
-    exit 1
+  echo -e "\033[1;31mUsage: git start <branch-name>\033[0m"
+  exit 1
 fi
 
 # check if our ssh-agent has our key loaded
 ssh-add -l | grep -q "no identities"
 if [ $? -eq 0 ] ; then
-    ssh-add || exit 1
+  ssh-add || exit 1
+fi
+
+username=$(gh api user --jq .login)
+if [ -z "$username" ] ; then
+  echo -e "\033[1;31mCould not determine GitHub username. Make sure you are logged in with 'gh auth login'.\033[0m"
+  exit 1
+fi
+
+# strip prefix with / and add username as prefix to branch name
+dir_name="${1##*/}"
+branch_name="$username/$dir_name"
+main=$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')
+is_bare_repo=$(git rev-parse --is-bare-repository)
+if [ "$is_bare_repo" = "true" ] ; then
+  set -e
+  git fetch origin
+  git worktree add -b "$branch_name" "$dir_name"
+  cd "$dir_name"
+  git rebase "origin/$main"
+  exit 0
+fi
+
+git diff --quiet && git diff --cached --quiet
+if [ $? -ne 0 ] ; then
+  echo -e "\033[1;31mYou have uncommitted changes. Please commit or stash them before running git-sync.\033[0m"
+  exit 1
 fi
 
 set -e
 
-branch_name="$username/$1"
-main=$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')
-git checkout "$main"
-git sync
-git checkout -b "$branch_name"
+git fetch origin
+git checkout -b "$branch_name" "origin/$main"
